// Clock on E3
set_property PACKAGE_PIN E3 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports clock]

// Rest Signal
set_property PACKAGE_PIN N17 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

// VGA Port
set_property PACKAGE_PIN D8 [get_ports {VGA_B[3]}]
set_property PACKAGE_PIN D7 [get_ports {VGA_B[2]}]
set_property PACKAGE_PIN C7 [get_ports {VGA_B[1]}]
set_property PACKAGE_PIN B7 [get_ports {VGA_B[0]}]
set_property PACKAGE_PIN A6 [get_ports {VGA_G[3]}]
set_property PACKAGE_PIN B6 [get_ports {VGA_G[2]}]
set_property PACKAGE_PIN A5 [get_ports {VGA_G[1]}]
set_property PACKAGE_PIN C6 [get_ports {VGA_G[0]}]
set_property PACKAGE_PIN A4 [get_ports {VGA_R[3]}]
set_property PACKAGE_PIN C5 [get_ports {VGA_R[2]}]
set_property PACKAGE_PIN B4 [get_ports {VGA_R[1]}]
set_property PACKAGE_PIN A3 [get_ports {VGA_R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]

// Sync Ports
set_property PACKAGE_PIN B11 [get_ports hSync]
set_property PACKAGE_PIN B12 [get_ports vSync]
set_property IOSTANDARD LVCMOS33 [get_ports hSync]
set_property IOSTANDARD LVCMOS33 [get_ports vSync]

// PS2 Stuff
set_property PACKAGE_PIN F4 [get_ports ps2_clk]
set_property PACKAGE_PIN B2 [get_ports ps2_data]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_data]

set_property PACKAGE_PIN P18 [get_ports down]
set_property PACKAGE_PIN P17 [get_ports left]
set_property PACKAGE_PIN M17 [get_ports right]
set_property PACKAGE_PIN M18 [get_ports up]
set_property IOSTANDARD LVCMOS33 [get_ports left]
set_property IOSTANDARD LVCMOS33 [get_ports right]
set_property IOSTANDARD LVCMOS33 [get_ports up]
set_property IOSTANDARD LVCMOS33 [get_ports down]

set_property PACKAGE_PIN T10 [get_ports {LED_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[0]}]
set_property PACKAGE_PIN R10 [get_ports {LED_out[5]}]
set_property PACKAGE_PIN K16 [get_ports {LED_out[4]}]
set_property PACKAGE_PIN K13 [get_ports {LED_out[3]}]
set_property PACKAGE_PIN P15 [get_ports {LED_out[2]}]
set_property PACKAGE_PIN T11 [get_ports {LED_out[1]}]
set_property PACKAGE_PIN L18 [get_ports {LED_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {whichLED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {whichLED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {whichLED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {whichLED[0]}]
set_property PACKAGE_PIN J14 [get_ports {whichLED[3]}]
set_property PACKAGE_PIN T9 [get_ports {whichLED[2]}]
set_property PACKAGE_PIN J18 [get_ports {whichLED[1]}]
set_property PACKAGE_PIN J17 [get_ports {whichLED[0]}]

set_property PACKAGE_PIN U13 [get_ports {whichLED[7]}]
set_property PACKAGE_PIN K2 [get_ports {whichLED[6]}]
set_property PACKAGE_PIN T14 [get_ports {whichLED[5]}]
set_property PACKAGE_PIN P14 [get_ports {whichLED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {whichLED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {whichLED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {whichLED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {whichLED[4]}]

set_property IOSTANDARD LVCMOS33 [get_ports sf]
set_property PACKAGE_PIN V11 [get_ports sf]
set_property IOSTANDARD LVCMOS33 [get_ports {reg1[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg1[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg1[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg1[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg1[0]}]
set_property PACKAGE_PIN H17 [get_ports {reg1[0]}]
set_property PACKAGE_PIN K15 [get_ports {reg1[1]}]
set_property PACKAGE_PIN J13 [get_ports {reg1[2]}]
set_property PACKAGE_PIN N14 [get_ports {reg1[3]}]
set_property PACKAGE_PIN R18 [get_ports {reg1[4]}]
set_property PACKAGE_PIN V17 [get_ports {reg1[5]}]
set_property PACKAGE_PIN U17 [get_ports {reg1[6]}]
set_property PACKAGE_PIN U16 [get_ports {reg1[7]}]
set_property PACKAGE_PIN V16 [get_ports {reg1[8]}]
set_property PACKAGE_PIN T15 [get_ports {reg1[9]}]
set_property PACKAGE_PIN U14 [get_ports {reg1[10]}]
set_property PACKAGE_PIN T16 [get_ports {reg1[11]}]
set_property PACKAGE_PIN V15 [get_ports {reg1[12]}]
set_property PACKAGE_PIN V14 [get_ports {reg1[13]}]
set_property PACKAGE_PIN V12 [get_ports {reg1[14]}]
